routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/info-1230', function () {
    phpinfo();
    exit;
});

Route::get('/dashboard', function () {
    echo "<h1>entrou</h1>";
});

// Password reset link request routes...
Route::get('password/email', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.email');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');

// Password reset routes...
Route::get('password/reset', 'Auth\ResetPasswordController@showResetForm')->name('password.request');
Route::post('password/reset', 'Auth\ResetPasswordController@postReset')->name('password.reset');
Route::get('password-reset', 'Auth\ResetPasswordController@viewPasswordReset')->name('password.reset');

Auth::routes();

Route::middleware(["auth"])->group(function()
{
    Route::get('/home', 'HomeController@home')->name('home');
    Route::get('/admin/users', 'UsersController@index')->name('user.index');
    Route::get('/admin/courses', 'CoursesController@index')->name('courses.index');
//    Route::get('/admin/meditations', 'MeditationsController@index')->name('courses.index');
    Route::get('/admin/user/{uuid}/details', 'UsersController@userDetails')->name('user-details');
    Route::get('/user/{uuid}/set-as-admin', 'UsersController@userSetAsAdmin')->name('user.set-as-admin');
    Route::get('/user/{uuid}/remove-from-admin', 'UsersController@userRemoveFromAdmin')->name('user.remove-from-admin');

    Route::resource('user', 'UsersController');
    Route::get("/admin/tricks","TricksController@adminGroupTricks")->name('trick.index');
    Route::get('/admin/tricks/{id}', 'TricksController@adminGroupTricksDetail')->name('trick.group-detail');
    Route::get('/admin/tricks/{groupId}/trick/{id}', 'TricksController@adminTricksDetail')->name('trick.detail');
    Route::put('/admin/trick/{id}', 'TricksController@adminTricksEdit')->name('trick.update');

    Route::post("/admin/tricks","TricksController@adminTricksSave")->name('trick.trick-action');


    Route::post("/admin/tricks/step","TricksController@submitFormStep")->name('trick.step-action');
    Route::post("/admin/tricks/step/delete","TricksController@deleteFormStep")->name('trick.step-delete');

    Route::post("/admin/tricks/tip","TricksController@submitFormTip")->name('trick.tip-action');
    Route::post("/admin/tricks/tip/delete","TricksController@deleteFormTip")->name('trick.tip-delete');
});


//Route::get('/home', function() {
//
//})->name('home')->middleware('auth');

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\BlockedUser;
use App\Firestore;
use App\Group;
use App\Mail\SendInvite;
use App\OneSignalNotification;
use App\Pet;
use App\PetBreed;
use App\Tag;
use App\Timeline;
use App\TimelineReport;
use App\UserFollow;
use App\UserInvite;
use App\UserNotification;
use App\UserReport;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Tymon\JWTAuth\JWT;
use Validator;
use App\User;
use Auth;
use App\Course;
use JWTAuth;
use App\UserGroups;
use App\CourseSignature;
use Illuminate\Support\Facades\Redirect;
use Storage;
use File;
use Mail;
use Webpatser\Uuid\Uuid;

class UsersController extends Controller
{

    public function index()
    {
        $users = User:: orderBy('name')->
                        paginate();
        return view('user.index', compact('users'));
    }

    public function destroy($id) {
        $loggedUser = Auth::user();
        $user = User::findOrFail($id);
        if( $loggedUser->is_admin == true || $loggedUser->id != $user->id) {
            $user->delete();
            return response()->redirectToRoute('user.index', $user->uuid)->with('success', "User removed");
        }
        exit();

    }

    public function apiCreateUser(Request $request)
    {
        $data = $request->all();
        $rules = [
            'name'      => 'required',
            'password'  => 'required|min:8',
            'email'     => 'required|email|unique:users,email',
        ];

        $validator = Validator::make($data,$rules);
        $error = "";
        if ($validator->fails()) {
            $messages = $validator->messages()->all();
            return response()->json(['message' => $messages[0]], $this->requestNotAcceptable);
        } else {

            $data["password"] = bcrypt($data["password"]);
            $data["uuid"] = Uuid::generate(4);

            $user = User::create($data);

            $credentials = request(['email', 'password']);
            $token = JWTAuth::attempt($credentials);

            $dataEmail = ["user_name"=> $user->name];
            $sendEmail = Mail:: to($user->email)->
                                send(new \App\Mail\WelcomeMail($dataEmail));

            return response()->json([   'access_token' => $token,
                                        'user'  => $user,
                                    ]);
        }
    }

    public function apiEditUser(Request $request)
    {
        $user = Auth::user();
        $data = $request->all();
        $rules = [
            'password'  => 'min:8',
            'email'     => 'email|unique:users,email,'.$user->id,
        ];

        $validator = Validator::make($data,$rules);

        if ($validator->fails()) {
            $messages = $validator->messages()->all();
            if (count($messages) > 1) {
                return response()->json(['messages' => $messages], $this->requestNotAcceptable);
            } else {
                return response()->json(['message' => $messages[0]], $this->requestNotAcceptable);
            }
        } else {
            if (isset($data["password"])) {
                $data["password"] = bcrypt($data["password"]);
            }

            $user->update($data);

            $image  = $request->file("image");
            if($request->hasFile("image") &&  $image->isValid()) {
                $this->uploadFile($user, $image);
            }

            return response()->json(['user' => $user]);
        }
    }

    public function apiUserPets($id)
    {

        $pet = Pet::whereUserId($id)->
                    with(["breed","breed.type"])->
                    get();

        $user = User::findOrFail($id);

        if($user->is_blocked) {
            return response()->json(null, 404);
        }

        return $pet;
    }

    public function apiSetDefaultTags(Request $request) {
        $tags = $request->input("tags");
        if (!empty($tags) && count($tags)) {
            $tags = Tag::stringToTags($tags);
            $user = Auth::user();
            $user->addTagRelation($tags);
            $user->tags;

            return response()->json(['user' => $user], $this->requestCreatedSuccess);
        } else {
            return response()->json(['message' => "Select one tag"], $this->requestNotAcceptable);
        }
    }

    public function userDetails($uuid)
    {
        $user = User::where("uuid","=", $uuid)->
                      first();
        if ($user) {
            $userInfo = [];
            return view('user.details', compact('userInfo','user'));
        } else {
            return Redirect::back()->with('error', "User not found");
        }

    }

    public function userSetAsAdmin($uuid)
    {
        $user = User::byUUID($uuid);
        if ($user) {
            $user->is_admin = true;
            $user->update();
            return response()->redirectToRoute('user-details', $user->uuid)->with('success', "User updated");
        } else {
            return Redirect::back()->with('error', "User not found");
        }
    }

    public function userRemoveFromAdmin($uuid)
    {
        $user = User::byUUID($uuid);
        if ($user) {
            $user->is_admin = false;
            $user->update();
            return response()->redirectToRoute('user-details', $user->uuid)->with('success', "User updated");
        } else {
            return Redirect::back()->with('error', "User not found");
        }
    }

    public function apiReport(Request $request)
    {
        $user = Auth::user();
        $data = $request->all();
        $reported = User::findOrFail($request->input("id"));
        $report = UserReport::create([  "user_id"       => $user->id,
                                        "reported_id"   => $reported->id,
                                        "reason"        => $request->input("reason",""),
                                        "comment"       => $request->input("comment","")]);
        if (!UserReport::where("user_id","=", $user->id)->where("reported_id","=", $reported->id)->exists()) {
            if ($report) {
//                $sendEmail = Mail:: to("jsinoti@gmail.com")->
//                            send(new \App\Mail\TimelineReport());
                return response()->json(["message" => "Usuário reportado com sucesso."], $this->requestAcceptedSuccess);
            }
        }
        return response()->json(["error" => "Usuário já reportado anteriormente"], $this->requestNotAcceptable);
    }


    public function apiDetailsUser(Request $request, $id)
    {
        $user = User::find($id);

        if ($user->is_blocked) {
            return response()->json(null, 404);
        }

        if ($user) {
            $user = $user->toArray();
            $user["pets"] = Pet::   with(["breed","breed.type"])->
                                    whereUserId($id)->get();
            $user["following"] = UserFollow::whereUserId($id)->count();
            $user["groups"] = UserGroups::whereUserId($id)->count();
            $user["courses"] = CourseSignature::whereUserId($id)->count();
            return response()->json(['user' => $user]);
        } else {
            return response()->json(['message' => __("User not found")], $this->requestNotAcceptable);
        }
    }

    public function apiFollowUser(Request $request)
    {
        $user = Auth::user();
        $petId = $request->input("pet_id");

        $pet = Pet::findOrFail($petId);
        if($pet->tutor->is_blocked) {
            return response()->json(null, 404);
        }

        $isToFollow = $request->input("follow");
        $userFollow = UserFollow::  where("user_id", "=", $user->id)->
                                    where("pet_id", "=", $petId)->first();

        if ((bool)$isToFollow) {
            if (!$userFollow) {
                $pet = Pet::findOrFail($petId);

                UserFollow::create(["user_id" => $user->id, "pet_id" => $petId]);

                if ($user->id != $pet->user_id) {
                    UserNotification::create([  'action'        => 'follow',
                                                'notified_id'   => $pet->user_id,
                                                'user_id'       => $user->id,
                                                'pet_id'        => $petId,
                                                "message"       => "começou a seguir"]);

                    if (!is_null($pet->tutor->onesiginal_token)) {
                        OneSignalNotification::sendPushNotification($user->name. " começou a seguir ". $pet->name.".",
                            $pet->tutor->onesiginal_token);
                    }
                }

            }
            return response()->json(['message' => __("Solicitação realizada com sucesso")]);
        } else {
            if ($userFollow) {
                $userFollow->delete();
            }
            return response()->json(['message' => __("Solicitação realizada com sucesso")]);
        }
    }

    public function apiUserFollowed(Request $request, $id)
    {

        $user = User::findOrFail($id);
        if($user->is_blocked) {
            return response()->json(null, 404);
        }

        $usersBlockedMe = BlockedUser:: whereBlockedId(Auth::user()->id)->
                                        pluck("user_id")->
                                        toArray();

        $usersIBlocked = BlockedUser::  whereUserId(Auth::user()->id)->
                                        pluck("blocked_id")->
                                        toArray();

        $userFollowed = Pet::   select("pets.*")->
                                with(["tutor"])->
                                join("users","users.id",'=','pets.user_id')->
                                leftJoin('user_follows', 'pets.id', '=', 'pet_id')->
                                whereNotIn("pets.user_id", $usersBlockedMe)->
                                whereNotIn("pets.user_id", $usersIBlocked)->

resources/views/user/details.blade.php
@extends('adminlte::page')

@section('title', 'Pataki')

@section('content_header')
    <h1 class="m-0 text-dark">Usuário</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-md-3">
            <!-- Profile Image -->
            <div class="card card-primary card-outline">
                <div class="card-body box-profile">
                    <div class="text-center">
                        <img class="profile-user-img img-fluid img-circle" src="{{$user->image_path}}" alt="User profile picture">
                    </div>

                    <h3 class="profile-username text-center">{{$user->name}}</h3>

                    <p class="text-muted text-center"><a href="mailto:{{$user->email}}">{{$user->email}}</a></p>

{{--                    <ul class="list-group list-group-unbordered mb-3">--}}
{{--                        <li class="list-group-item">--}}
{{--                            <b>Followers</b> <a class="float-right">{{$userInfo["followers"]}}</a>--}}
{{--                        </li>--}}
{{--                        <li class="list-group-item">--}}
{{--                            <b>Following</b> <a class="float-right">{{$userInfo["following"]}}</a>--}}
{{--                        </li>--}}
{{--                        <li class="list-group-item">--}}
{{--                            <b>Meditations</b> <a class="float-right">{{count($userInfo["meditations"])}}</a>--}}
{{--                        </li>--}}
{{--                        <li class="list-group-item">--}}
{{--                            <b>Courses</b> <a class="float-right">{{$userInfo["courses"]}}</a>--}}
{{--                        </li>--}}
{{--                        <li class="list-group-item">--}}
{{--                            <b>Groups</b> <a class="float-right">{{$userInfo["groups"]}}</a>--}}
{{--                        </li>--}}
{{--                    </ul>--}}
                    @if ($user->is_admin)
                        <a href="{{route("user.remove-from-admin", $user->uuid)}}" class="btn btn-danger btn-block"><b>Remove from admin</b></a>
                    @else
                        <a href="{{route("user.set-as-admin", $user->uuid)}}" class="btn btn-success btn-block"><b>Set as admin</b></a>
                    @endif
                    <form id="removeUser"
                          action="{{ route('user.destroy', $user->id) }}"
                          class="form-horizontal confirm"
                          method="post" style="display: inline-block">
                        {!! csrf_field() !!}
                        <input type="hidden" name="_method" value="DELETE">

                    </form>
                    <button class="btn btn-danger btn-block mt-2" onclick="removeUser()"><b>Remover usuário</b></button>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->

        </div>
        <!-- /.col -->
        <div class="col-md-9">
            <div class="card">
                <div class="card-header p-2">
                    <ul class="nav nav-pills">
                        <li class="nav-item"><a class="nav-link active" href="#timeline" data-toggle="tab">Timeline</a></li>
                    </ul>
                </div><!-- /.card-header -->
                <div class="card-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="timeline">
{{--                            @foreach($userInfo["activities"] as $timeline)--}}
{{--                            <!-- Post -->--}}
{{--                            <div class="post">--}}
{{--                                <p>{{$timeline->desc}}</p>--}}
{{--                                @if($timeline->image_path)--}}
{{--                                    <div class="row mb-3">--}}
{{--                                        <div class="col-sm-6">--}}
{{--                                            <img class="img-fluid" src="{{$timeline->image_path}}" alt="Photo">--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                @endif--}}
{{--                                <p>--}}
{{--                                    <label><i class="far fa-comments mr-1"></i> Comments: </label> {{$timeline->tot_comment}}<br>--}}
{{--                                    <label><i class="far fa-thumbs-up mr-1"></i> Bless:</label> {{$timeline->tot_bless}}--}}
{{--                                </p>--}}
{{--                                <span class="description">Sent - {{$timeline->created_at->diffForHumans()}}</span>--}}
{{--                            </div>--}}
{{--                            <!-- /.post -->--}}
{{--                            @endforeach--}}
                        </div>
                        <!-- /.tab-pane -->
                        <div class="tab-pane" id="meditation">
                            <div class="row">
{{--                                @foreach($userInfo["meditations"] as $meditation)--}}
{{--                                    <div class="col-md-3">--}}
{{--                                        <div class="card">--}}
{{--                                            <div class="card-header" style="height: 180px; overflow: hidden;">--}}
{{--                                                <img src="{{$meditation->thumb_path}}" style="width: 100%">--}}
{{--                                            </div>--}}
{{--                                            <!-- /.card-header -->--}}
{{--                                            <div class="card-body">--}}
{{--                                                <p>{{$meditation->title}}</p>--}}
{{--                                                <p><label>Blesses:</label> {{$meditation->tot_bless}}</p>--}}
{{--                                                <small>{{$meditation->created_at->format('Y-m-d H:i')}}</small>--}}
{{--                                            </div>--}}
{{--                                            <!-- /.card-body -->--}}
{{--                                            <div class="card-footer">--}}
{{--                                                <audio controls style="width: 100%">--}}
{{--                                                    <source src="{{$meditation->file_path}}" type="audio/mpeg">--}}
{{--                                                    Your browser does not support the audio element.--}}
{{--                                                </audio>--}}
{{--                                            </div>--}}
{{--                                            <!-- /.card-footer -->--}}
{{--                                        </div>--}}
{{--                                    </div>--}}
{{--                                @endforeach--}}
                            </div>
                        </div>
                        <!-- /.tab-pane -->

                        <div class="tab-pane" id="courses">
                            <div class="row">
                                @foreach($user->courses as $course)
                                    <div class="col-md-3">
                                        <div class="card">
                                            <div class="card-header" style="height: 180px; overflow: hidden;">
                                                @if($course->image_path)
                                                    <img src="{{$course->image_path}}" style="width: 100%; background: grey;">
                                                @else
                                                    <div style="background: grey; width: 100%; height: 100%"></div>
                                                @endif
                                            </div>
                                            <!-- /.card-header -->
                                            <div class="card-body">
                                                <p>{{$course->name}}</p>
                                                <p><label>Prices:</label> R$:
                                                    @if($course->price)
                                                        {{$course->price->price/100}}
                                                    @else
                                                        0.00
                                                    @endif
                                                </p>

                                                @if($course->signatures)
                                                    <p><label>Signatures:</label> {{$course->signatures()->count()}}</p>
                                                @endif

                                                <small>{{$course->created_at->format('Y-m-d H:i')}}</small>
                                            </div>
                                            <!-- /.card-footer -->
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                        <!-- /.tab-pane -->
                    </div>
                    <!-- /.tab-content -->
                </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
    </div>
@stop

@section('css')
    <style>
        .meditation-img {
            display: block;
            max-width: 100%;
            max-height: 100%;
            width: auto;
            height: auto;
        }
    </style>

@stop

@section('js')
    <script>
        function removeUser() {
            if(confirm("Deseja remover o usuário?")) {
                $("#removeUser").submit();
            }
        }
    </script>
@stop

resources/views/user/index.blade.php
@extends('adminlte::page')

@section('title', 'Pataki')

@section('content_header')
    <h1 class="m-0 text-dark">Users list</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title"></h3>
                    <div class="card-tools">
{{--                        <div class="input-group input-group-sm" style="width: 150px;">--}}
{{--                            <input type="text" name="table_search" class="form-control float-right" placeholder="Search">--}}

{{--                            <div class="input-group-append">--}}
{{--                                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>--}}
{{--                            </div>--}}
{{--                        </div>--}}
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive p-0">
                    <table class="table table-hover text-nowrap">
                        <thead>
                        <tr>
                            <th>Code</th>
                            <th>User</th>
                            <th>E-mail</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                        <tr>
                            <td width="50">{{$user->uuid}}</td>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td><a href="{{route("user-details", $user->uuid)}}" class="btn btn-success btn-block"><b>Details</b></a></td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer clearfix">
                    {{ $users->links() }}
                </div>
                <!-- /.card-body -->
            </div>
        </div>
    </div>
@stop

@section('css')

@stop

@section('js')

@stop